# Name: Ashes (dark)
# Author: Chris Kempson

[colors.primary]
background = "#000000"
foreground = "#c7ccd1"

[colors.cursor]
text = "#1c2023"
cursor = "#c7ccd1"

[colors.normal]
black = "#000000"
red = "#c7ae95"
green = "#95c7ae"
yellow = "#aec795"
blue = "#ae95c7"
magenta = "#c795ae"
cyan = "#95aec7"
white = "#c7ccd1"

[colors.bright]
black = "#000000"
red = "#c7ae95"
green = "#95c7ae"
yellow = "#aec795"
blue = "#ae95c7"
magenta = "#c795ae"
cyan = "#95aec7"
white = "#f3f4f5"
